### ISSUE TITLE
Package problem: inadyn

### ISSUE THREAD

**Issue by xmun2k** [Entware-ng/Entware-ng#108]
I have the latest inadyn package installed from entware-ng on QNAP TS-421 running on ARMv5. There seems to be a problem as no matter what configuration file is used an error message is displayed. Even using sample configurations yields the same results. 
Running the application using the -v parameter to display the version shows that this is a beta build. Could it be replaced by an official build?

**Comment by zyxmon** [comment]
You can download and install the previous package that works:

```
 wget http://pkg.entware.net/binaries/armv5/archive/inadyn_1.99.14-20150722-1_armv5soft.ipk
opkg install ./inadyn_1.99.14-20150722-1_armv5soft.ipk
rm ./inadyn_1.99.14-20150722-1_armv5soft.ipk
```

**Comment by ryzhovau** [comment]
Some options like `background` has been [changed](https://github.com/troglobit/inadyn/commit/508081a4fb1caea27cc44c32ddd26d7e9ce6eefe) recently. Please, refer to original documentations.

> Could it be replaced by an official build?

AFAIK, official `inadyn` was abandoned couple of years ago and doesn't work with some DDNS services because their API changed.

**Comment by ryzhovau** [comment]
Nevermind. We've downgraded `inadyn` fork down to last stable release.
