### ISSUE TITLE
rdiff-backup

### ISSUE THREAD

**Issue by ryzhovau** [Entware-ng/Entware-ng#14]

**Comment by pkim22** [comment]
Replying to my own request -

For those of you wanting to use rdiff-backup - I strongly encourage you to move on to rsnapshot.

I made the move to rsnapshot because of several reasons:

1. rsnapshot is already supported by entware!
2. rsnapshot is still being developed! Bugfixes and new features are being added upstream.
3. rsnapshot is CPU efficient and much faster - instead of running SHA comparison for each file and also compressing the new "difference archive," rsync is used to detect and sync. It results in much faster backup which also uses less CPU.
4. Exponential backoff of backup archives - e.g. you can keep hourly backups for recent backups, but monthly backups for old backups and anything in-between - this is pretty space-efficient
5. Because of the way rsnapshot works (using hardlinks), each backup directory is complete and accessible. You don't need to use the tool to grab a specific version from a specific archive. In rdiff-backup, you can only see the latest and any past archive needs to be extracted by rdiff-backup tool.
6. You can still do unattended, automatic backups - you can use a no-password ssh logon and limit the ssh login to specific actions (same as rdiff-backup). I'm doing a "pull backup" from an NAS right now for a couple of linux boxes.

Some difficulties of using rsnapshot:
1. Have to learn the syntax and ins and outs of rsnapshot.conf
2. No separate command for backing up from different sources - everything in one file (rsnapshot.conf) - I think there is a hack to support individual conf files, but it's not how it was intended to be used.
