### ISSUE TITLE
Would u pls update shadowvpn?

### ISSUE THREAD

**Issue by tkjune** [Entware-ng/Entware-ng#183]
The latest version 0.2.0 supports multiple user. Can be forked here:
https://github.com/aa65535/openwrt-shadowvpn
(The original source has been deleted for censorship reason :( )
Thank you.

**Comment by ryzhovau** [comment]
I [deleted](https://github.com/Entware-ng/rtndev/commit/9f1e4bc322cb87afa1a2523d3fcb95a1a37939b3) `shadowvpn` because sources was deleted.
Like it or not, that was done by legitimate reasons.

I don't want Entware to be closed by the same reasons. We can't risk the entire repo in a favor of one package, sorry.

**Comment by tkjune** [comment]
Just to clarify, The source was deleted by the author himself, not for "copyright" issue, but under the censorship force from chn gov. Means it won't d affect other country.  but thanks anyway for previous work on this.

**Comment by ryzhovau** [comment]
AFAIR, Chinia gov required to delete sources from here, isn't it?

**Comment by tkjune** [comment]
yes. the gov can not give orders to git hub, but they force the author by himself. coz the author is chinese and live in china.

**Comment by ryzhovau** [comment]
Done.

**Comment by tkjune** [comment]
Thank you!
