### ISSUE TITLE
Package Request: iptables frontend ( i.e Firewalld )

### ISSUE THREAD

**Issue by aidan160** [Entware-ng/Entware-ng#230]
It would be awsome if FirewallD would be added to the package manager would make my life much easier. Or and other front end like UFW but FirewallD is IMO much better.

**Comment by ryzhovau** [comment]
Entware is firmware Independent repo, we can't rely on specific iptables rules and\or network interfaces. There is too much differences between embedded devices, even `iptables` package sometimes is not working correctly because of  kernel differences.

I see no sense to add any iptables front-end, sorry.
