### ISSUE TITLE
Missing lib2to3 module in Python?

### ISSUE THREAD

**Issue by programatix** [Entware-ng/Entware-ng#268]
Hi,

I recently installed new packages for python and I get the following errors (snippet),
```
Traceback (most recent call last):
...
  File "/opt/lib/python2.7/site-packages/past/translation/__init__.py", line 41, in <module>
    from lib2to3.pgen2.parse import ParseError
ImportError: No module named lib2to3.pgen2.parse
```

The error is caused by an attempt to import `lib2to3` module,
```
from lib2to3.pgen2.parse import ParseError
from lib2to3.refactor import RefactoringTool
```

I was told that Python can be compiled with or without `lib2to3`. Is it possible to have a python version with `lib2to3` module?

thanks.

**Comment by zyxmon** [comment]
We do not have Python3 and do not include lib2to3 that is beta. Your problem is solved by commenting 2 lines as shown in FlexGet issue you referenced
http://discuss.flexget.com/t/felxget-2-0-2-importerror-no-module-named-lib2to3-pgen2-parse/2252/9

**Comment by zyxmon** [comment]
This package (python3-lib2to3) was added to Entware with Python3.

**Comment by ailjushkin** [comment]
I found it interesting and want to report about this here.
Somehow, I got this error because the lib2to3 package is in the Lib/site-packages folder AND (!) in the Lib folder (which is as I see is basic and correct package of lib2to3).

How lib2to3 package got into the site-packages folder - that is the question which I didn't answer yet.

So when I open my windows console and type `import lib2to3.refactor` it executes correctly.
But when I run my code in Pycharm, which firstly automatically adds Lib/site-packages folder into the `PYTHONPATH` then site-packages lib2to3 picked up and there is no refactor module physically.

So you probably note this in future.
