### ISSUE TITLE
Package request: asterisk-gui (SVN version)

### ISSUE THREAD

**Issue by evs38** [Entware-ng/Entware-ng#388]
Please include into telephony/admin feed the package asterisk-gui. As seen in #373, the package was broken at OpenWrt feed because its source file was removed by Digium. But it can be obtained via SVN from http://svn.digium.com/svn/asterisk-gui/branches/2.0/ and working very well with Asterisk 11.x and 13.x. Also it is still included in Optware-ng.
OpenWrt broken packages are there: https://git.openwrt.org/?p=feed/telephony.git;a=tree;f=admin;hb=HEAD

**Comment by ryzhovau** [comment]
`asterisk-gui` was removed because it's not working as expected. There's buggy paths in bunch of scripts after cross-compilation. Also, some of `asterisk` components wasn't installed in OpenWrt, so using `asterisk-gui` become painful. 

We decided it brings more "evil" then "good" to repo:) So it was reasonable excluded.
Feel free to use our make files and patches if you wish to revive it.
