### ISSUE TITLE
Proper way to update opkg itself

### ISSUE THREAD

**Issue by ksze** [Entware-ng/Entware-ng#714]
What's the proper way to update entware-ng itself?

Do I just re-download and re-run `entware_install.sh`?

Do I need to reboot?

In fact, how do I even tell whether my entware-ng base installation is up-to-date?

Currently, `opkg --version` on my system says "opk version 0.1.8", but there is no version tagging or any "release" in this git repo.

The wiki doesn't seem to cover updating entware-ng itself.

**Comment by zyxmon** [comment]
Entware is a repository of packages. Just update packages with 'opkg update' & 'opkg upgrade'.

**Comment by ksze** [comment]
> Entware is a repository of packages.

Fair enough.

But what about the opkg command line tool then? Does it somehow update itself via `opkg update` and `opkg upgrade`?

**Comment by ryzhovau** [comment]
`opkg` is a static binary, deployed by installation script. This is by design to avoid mis-linkage situation like #700, #691, #680, #675, #225, #52 and so on or it can be handy when whole Entware-ng installation is almost ruined (`opkg` stays alive then). On the other hand, you might stuck on old `opkg` version because it's not updated by `opkg upgrade`. 

If you still want to update `opkg` itself, try `opkg install opkg`. Use it at your own risk.

**Comment by zyxmon** [comment]
opkg is linked dynamically for arm & intel installations. It is installed as a package with the latest arm and intel installation scripts. Earlier opkg versions have some bugs. If you encounter bugs with opkg you can `opkg install opkg`.
