### ISSUE TITLE
Package request: simple-obfs

### ISSUE THREAD

**Issue by ohmyarch** [Entware-ng/Entware-ng#719]
### Package: simple-obfs

Intro: A simple obfusacting tool, designed as plugin server of shadowsocks.
Repo: https://github.com/shadowsocks/simple-obfs
License: GPLv3 or any later version of GPL

### Platform: ASUS RT-68U, Asuswrt-Merlin, ARMv7

**Comment by maxduke** [comment]
I would like to request the same. This package is a plugin for package shadowsocks-libev.

**Comment by yicong2007** [comment]
I would like to request the same. 
Before the package is officially added into entware-ng, we can follow the [simple-obfs for OpenWrt](https://github.com/aa65535/openwrt-simple-obfs) by @aa65535 and  make an entware-ng version for our own. 

**I have just compiled obfs-local and use it in my RT-AC68U, it works fine for now. The following is HOW.** 

Follow [How to add a new package](https://github.com/Entware-ng/Entware-ng/wiki/How-to-add-a-new-package) to prepare the build environment. Compile shadowsocks-libev **_3.0.6-2 and install them first, this can confirm that you had prepare the build environment correctly. 
Then `cd` to the Entware-ng folder and download the Makefile created by @aa65535 
```
git clone https://github.com/aa65535/openwrt-simple-obfs.git feeds/packages/net/simple-obfs
```
Apply the following patch to the `feeds/packages/net/simple-obfs/Makefile` (we should change the install directory since we use /opt/bin instead of /usr/bin in Entware-ng. I also add submenu to keep the simple-obfs in the same submenu as shadowsocks-libev. )
```
@@ -33,6 +33,7 @@
 define Package/simple-obfs/Default
 	SECTION:=net
 	CATEGORY:=Network
+	SUBMENU:=Web Servers/Proxies
 	TITLE:=Simple-obfs
 	URL:=https://github.com/shadowsocks/simple-obfs
 	DEPENDS:=+libev +libudns +libpthread +libsodium
@@ -50,13 +51,13 @@
 CONFIGURE_ARGS += --disable-ssp --disable-documentation --disable-assert
 
 define Package/simple-obfs/install
-	$(INSTALL_DIR) $(1)/usr/bin
-	$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/obfs-local $(1)/usr/bin
+	$(INSTALL_DIR) $(1)/opt/bin
+	$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/obfs-local $(1)/opt/bin
 endef
 
 define Package/simple-obfs-server/install
-	$(INSTALL_DIR) $(1)/usr/bin
-	$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/obfs-server $(1)/usr/bin
+	$(INSTALL_DIR) $(1)/opt/bin
+	$(INSTALL_BIN) $(PKG_BUILD_DIR)/src/obfs-server $(1)/opt/bin
 endef
 
 $(eval $(call BuildPackage,simple-obfs))
```
Use `make package/symlinks` to update the packages, use `make menuconfig` to enable `simple-obfs` and/or `simple-obfs-server`. 
At last, use `make package/simple-obfs/compile` to compile. 
If nothing got wrong, you would find `simple-obfs-server_0.0.3-1_armv7soft.ipk` and `simple-obfs_0.0.3-1_armv7soft.ipk` in the `Entware-ng/bin/targets/armv7soft/generic-glibc/packages` folder. 
Use `opkg install` to install the ipks in your router.

**Comment by zyxmon** [comment]
If it is still needed, please report.
Now we have shadowsocksR-libev in repo - https://github.com/Entware-ng/Entware-ng/issues/736

**Comment by maxduke** [comment]
Thanks zyxmon. But the package is still needed for package shadowsocks-libev for full functionality.  ( shadowsocksR-libev != shadowsocks-libev + simple-obfs )

**Comment by zyxmon** [comment]
simple-obfs is now in entware-3x - https://github.com/Entware-for-kernel-3x/rtndev-3x/tree/master/simple-obfs
binaries will be available soon.
I think it will be also added to Entware-ng
