### ISSUE TITLE
Samba 4.6 in Entware-ng

### ISSUE THREAD

**Issue by winyl77** [Entware-ng/Entware-ng#763]
Can we get Samba 4 to be compiled on Entware-ng. Can we get samba 4.6?
How hard would it be.

**Comment by TCB13** [comment]
+1 on this! thank you.

**Comment by zyxmon** [comment]
We will upgrade samba with upstream (openwrt packages). Please ask upstream.

**Comment by zyxmon** [comment]
I have compiled samba 4.7 for Entware-3x. It works.
If you can test it on Entware-3x please tell your feed (armv7, x64 ...) ?

**Comment by winyl77** [comment]
I have armv7 cortexa9 can test on it. I wonder if I have Entware 3.x, propably not. Must check.
I trying to compile samba 4.6.8 for 2.x kernel, but I'm stuck on pyhton-param depedicity.
I also have x64 nas, but I would have to install openwrt or else on it to test.

**Comment by zyxmon** [comment]
Entware-3x is here - https://github.com/Entware-for-kernel-3x/Entware-ng-3x
Broadcom cortex a9 routers have 2.6.36 kernels. You need kernel 3.x router or NAS.
Open an issue on Entware-3x "organization" if you install it.

**Comment by winyl77** [comment]
I have successfully cross-compiled samba 4.7.0. It needs heimdal package. I made Makefiles for Entware-ng cross build machinery. Tested on my cortex a9 router. It compiles, it works:)

**Comment by winyl77** [comment]
So there is samba-4.7.1 now. Recompile running now :) 
The new gcc-7.2 available in lede build machinery is producing even smaller package size.
Yes it compiles on lede too with my patches.

**Comment by Andy2244** [comment]
@winyl77 can you send me your heimdal/samba4 patches, makefile (feed) please? 
I'm trying to finally get samba4 into the official openwrt repo and while my samba4.7.4 version runs fine, i may as well try to add proper (AD-DC, ADS) support via heimdal.

I'm looking mainly for your gcc 5.5 patches/makefiles, since i try to keep the initial merge as light as possible, so no heavy patches. If all works gcc7 and size patches can be added later.

thx Andy
