### ISSUE TITLE
Package request: transmissiondcfp 

### ISSUE THREAD

**Issue by cfpp2p** [Entware-ng/Entware-ng#97]
> Ultimate repo for embedded devices

So maybe it would want ultimate bittorrent client for embedded devices? ;)

It's a fork of the official transmission and if that works so should transmissiondcfp. It's 2.77 core so from https://dev.openwrt.org/browser/packages/net/transmission?rev=35670  I edit Makefile and hope this might help you to enable it to work https://gist.github.com/cfpp2p/dc3b06184f840dc0a257    I don't know why it wouldn't https://dev.openwrt.org/log/packages/net/transmission?rev=40843

I put source http://downloads.sourceforge.net/project/transmissiondaemon/optware-ng-source/transmissiondcfp-2.77+14664-2.tar.bz2 in that Makefile. There are also two other of the same
https://github.com/cfpp2p/transmission/releases/download/2.77plus14664-2/transmissiondcfp-2.77plus14664-2.tar.bz2
http://transmissionbt.net/transmissiondcfp-2.77plus14664-2.tar.bz2.zip

Let me know what else you need for this to happen.

**Comment by ryzhovau** [comment]
We've sharing some info with @alllexx88 as long as we're hanging on the same forums. I've discovered your fork in September, here is my list of differences from original version:

* based on 2.77 plus some backports from newer versions (hierarchical file tree for example).
* `prefetch-magnets-enabled` - selecting content after magnet link added as in uTorrent.
* `piece-temp-dir` - saving downloaded, but unnecessary chunks.
* `reverify-torrents-tries` - forcing hash checking after download completed.
* dht.bootstrap - adding bootsrap DHT nodes.
*  `script-torrent-added-filename` - script hook, called after adding torrents.
* `stream-mode-default` - downloading video from the head of file to play it immediately after few chunks has been downloaded. 
* magnet link support in the watch dir.
* blacklist for UDP trackers.
* enhanced webseed settings.
* configurable Peer ID/User agent to fake torrent client ID.
* torrent grouping to apply different settings for different groups.
* enhanced IPv6 settings.
* `cheat-mode-default` for ration/seeding/leeching.

Thanks for the idea, but this issue was created by the author of transmission fork, not by user who asked to add something new to repo. At least, I have to wait a _user_ requests. 

As for me personally, I've found `transmissiondcfp` code too dirty to add to my repo, sorry. Also, I'm not going to support cheating transmission forks, so I closing this for now.

Still, no offense.

Regards, Alexander Ryzhov.

**Comment by cfpp2p** [comment]
> Thanks for the idea, but this issue was created by the author of transmission fork, not by user who asked to add something new to repo. At least, I have to wait a user requests. 

Fair enough, but I see no reason that I shouldn't promote my work. I believe in it's merits an want no reason to have others deprived of choice.

> As for me personally, I've found transmissiondcfp code too dirty to add to my repo, sorry. Also, I'm not going to support cheating transmission forks, so I closing this for now.

I've gone over similar ideas about *code too dirty* here https://trac.transmissionbt.com/ticket/532#comment:229 , so I won't do it repeat. As far a the rest it's all relative to the point of view what's ethical https://forum.transmissionbt.com/viewtopic.php?f=2&t=17722&hilit=%5Bthe+and%5D&sid=74106907bf0299abf5b73ad999196446 and besides you'll see disabling for public releases of 'hazardous' features.

> Still, no offense. I'm truly appreciate your contribution to original transmission development.

Thanks for Entware-ng. It's too bad about transmission development as we see a hint of the past complications that arose. https://forum.transmissionbt.com/viewtopic.php?f=1&t=17539&hilit=%5Bthe+and%5D#p72371
> ...The way I see it the project is very much alive, but hitting a bit of hard time at the moment...

I hope for the best future.

**Comment by ryzhovau** [comment]
I've tired to wait `script-torrent-added` implementation and [took](https://github.com/Entware-ng/entware-packages/commit/fd26868c3f0bd9cd4ee2f95adc4b2c1ce65368f8) your patch. Works fine, thank you!

**Comment by ryzhovau** [comment]
@cfpp2p, I decided to get another chance to compile `transmission-cfp` from trunk. It builds fine now, but I faced with some this issue https://github.com/cfpp2p/transmission/issues/7

Is there anything I can do about that?

**Comment by zyxmon** [comment]
The same on a different router with entware-3x (glibc, not uclibc):

Error: prefetch counter corrupt! prefetchCount value is 0 . Upload failed.

**Comment by cfpp2p** [comment]
@ryzhovau @zyxmon Please corroborate https://github.com/cfpp2p/transmission/commit/8e73c16a1801589c08df72029d18a609196788eb fixes the issue.

**Comment by zyxmon** [comment]
@cfpp2p - it looks like it fixed the issue in my case. I had no problems during 1 hour downloading.

**Comment by ryzhovau** [comment]
Few hours of seeding, no issues so far. Thanks!

@cfpp2p, what's in [release](https://github.com/cfpp2p/transmission/releases) archives? I've compared tagged code from git with tar.bz2 and found it quite different.

**Comment by cfpp2p** [comment]
transmissiondcfp-2.77plus14734-8.tar.bz2 is code for NSLU2 (http://www.nslu2-linux.org) and was used as well by https://github.com/alllexx88/Optware-ng. The differences mostly lie in port forwarding and upnp, https://github.com/cfpp2p/transmission/pull/2 and https://github.com/cfpp2p/transmission/pull/3

**Comment by ryzhovau** [comment]
Thanks for explanation. Package was added to Entware-ng repo with `web-client-cfp` enhanced WebUI. 

Also, you can use [our files](https://github.com/Entware-ng/rtndev/tree/master/transmission-cfp) for PR for OpenWrt guys.
